{% set name = "cliffordlayers" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/cliffordlayers/archive/v{{ version }}.tar.gz
  sha256: aa083cfd38122f6eebe1b60dc69b3f965e24aa866ce548eddbd74f163f7f657d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - pytest
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - cliffordlayers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/cliffordlayers
  doc_url: https://microsoft.github.io/cliffordlayers
  dev_url: https://github.com/microsoft/cliffordlayers
  summary: A PyTorch library for Clifford layers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weiji14
